# 1. Conexión a la Base de Datos
spring.datasource.url=jdbc:postgresql://localhost:5432/enviosp2p
spring.datasource.username=postgres
spring.datasource.password=12345
# (Cambia 'root' por tu contraseña de instalación de Postgres)

# 2. Driver
spring.datasource.driver-class-name=org.postgresql.Driver

# 3. Configuración de JPA / Hibernate
# 'update': Crea las tablas si no existen, o las actualiza si cambias el modelo.
# ¡Cuidado! En producción nunca se usa esto, pero para desarrollo es genial.
spring.jpa.hibernate.ddl-auto=update

# 4. Dialecto (Para que hable el idioma correcto de SQL)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# 5. Mostrar SQL en consola (Útil para aprender qué hace Hibernate por detrás)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=9727a4eb7742ac
spring.mail.password=4afd404c3c3553
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true